pushing to new branch
krzysztofsmokowski/jenkinscurlapp pull request #1
Opened 2017-12-10 15:44 UTC by krzysztofsmokowski

2017-12-10 15:59 UTC, Ogrodniczek requested changes
Please also add docstrings.

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +from datetime import datetime
Imports shall be in alphabetical order (google style guide)

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +        self.request = requests.get(url+'/job/'+job+'/api/json').json()
move this call to non public method or function

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +        self.request = requests.get(url+'/job/'+job+'/api/json').json()
Do you think this is a good name for a variable? Does it represent the data that is there?

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +            self.list_of_jsons.append(requests.get(url + '/api/json').json())
rethink if we shall separate requests call to other method or function.

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +        dt_obj = datetime.strptime(date, '%Y-%m-%d %H:%M')
it is an object anyway, do we want to have it in the name? Is it special?

Maybe we could move it to other non public method/function?

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +                    artifacts_list.append(self.url+'/job/'+self.job+'/lastSuccessfulBuild/artifact/'+artifact["fileName"])
this just looks too long.

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +    parser.add_argument("--job", help = 'specifying job of jenkins CI')
Are there some required arguments? Was the program tested? If there are some required artguments, we shall use https://docs.python.org/3/library/argparse.html#required

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +        what_to_print = jenkins.builds_urls()
That variable is not used anywhere, linter shall throw warning there.

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +        what_to_print = jenkins.artifact_printer(args.date)
same

2017-12-10 15:59 UTC, Ogrodniczek commented on app.py
> +                self.url_list.append(build["url"][:num])
these two fors could be wrapped to one function, rethink that. (code re-usability).

2017-12-10 16:14 UTC, krzysztofsmokowski commented on app.py
> +                    artifacts_list.append(self.url+'/job/'+self.job+'/lastSuccessfulBuild/artifact/'+artifact["fileName"])
I am not seeing possibilty of making it shorter

2017-12-10 16:15 UTC, Ogrodniczek commented on app.py
> +        for data in list_of_jsons:
Is data a proper variable name?

2017-12-10 16:17 UTC, Ogrodniczek commented on app.py
> +                    artifacts_list.append(self.url+'/job/'+self.job+'/lastSuccessfulBuild/artifact/'+artifact["fileName"])
You can extract the 'string creation' part to a different function and call it here.
In that function, if the string join will be still too long, you can break the lines so it will gain more readability.

2017-12-11 17:52 UTC, krzysztofsmokowski commented on app.py
> +        what_to_print = jenkins.builds_urls()
I don't understand, both args and jenkins are used for argparse functionality

2017-12-11 17:52 UTC, krzysztofsmokowski commented on app.py
> +        what_to_print = jenkins.artifact_printer(args.date)
I can't see possibility of making it in other way

2017-12-14 22:36 UTC, krzysztofsmokowski commented on app.py
> +        for data in list_of_jsons:
done

2017-12-14 22:36 UTC, krzysztofsmokowski commented on app.py
> +        what_to_print = jenkins.artifact_printer(args.date)
done

2017-12-14 22:36 UTC, krzysztofsmokowski commented on app.py
> +        what_to_print = jenkins.builds_urls()
done

2017-12-14 22:36 UTC, krzysztofsmokowski commented on app.py
> +    parser.add_argument("--job", help = 'specifying job of jenkins CI')
added required arguments

2017-12-14 22:37 UTC, krzysztofsmokowski commented on app.py
> +from datetime import datetime
done

2017-12-14 22:37 UTC, krzysztofsmokowski commented on app.py
> +        self.request = requests.get(url+'/job/'+job+'/api/json').json()
done

2017-12-14 22:37 UTC, krzysztofsmokowski commented on app.py
> +        self.request = requests.get(url+'/job/'+job+'/api/json').json()
done

2022-06-28 08:18 UTC, merged